name: Build and Test the Docker Image

on:
  # On each branch/commit
  push:
  # On each pull request
  pull_request:
  # Manually
  workflow_dispatch:

jobs:
  build:
    # No need to stick to an Ubuntu version
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ubuntu-hugo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: Build 18.04
        run: 'docker build --tag "${IMAGE_NAME}:18.04" --label "gha_run_number=${GITHUB_RUN_ID}" ./18.04/'
      - name: Install CST
        env:
          CST_VERSION: 1.15.0
        run: |
          curl --location --output=/usr/local/bin/container-structure-test "https://github.com/GoogleContainerTools/container-structure-test/releases/download/v${CST_VERSION}/container-structure-test-linux-amd64"
          chmod a+x /usr/local/bin/container-structure-test
          container-structure-test version
      - name: Test image 18.04
        run: container-structure-test test --image="${IMAGE_NAME}:18.04" --config tests.yaml
