name: Build and Test the Docker Image

on:
  # On each branch/commit/tags
  push:
  # On each pull request
  pull_request:
  # Manually
  workflow_dispatch:

jobs:
  build:
    # No need to stick to an Ubuntu version
    runs-on: ubuntu-latest
    # Allow GHA to push images in the GHCR registry
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ubuntu-hugo
      REGISTRY: ghcr.io
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - name: Define image name once for all (with sanitized tag value)
        run: |
          export REF_NAME="${{ github.ref_name }}"
          echo "FULL_IMAGE_NAME=${REGISTRY}/${IMAGE_NAME}:${REF_NAME//\//-}" >> $GITHUB_ENV
      - name: Build
        run: |
          docker build --tag "${FULL_IMAGE_NAME}" --label "gha_run_number=${GITHUB_RUN_ID}" ./
      - name: Install CST
        env:
          CST_VERSION: 1.15.0
        run: |
          curl --location --output /usr/local/bin/container-structure-test "https://github.com/GoogleContainerTools/container-structure-test/releases/download/v${CST_VERSION}/container-structure-test-linux-amd64"
          chmod a+x /usr/local/bin/container-structure-test
          container-structure-test version
      - name: Test image
        run: |
          container-structure-test test --image="${FULL_IMAGE_NAME}" --config tests.yaml
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: startsWith(github.ref, 'refs/tags')
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Image to GHCR
        if: startsWith(github.ref, 'refs/tags')
        run: |
          docker push "${FULL_IMAGE_NAME}"
